<?php
/**
 * Created by PhpStorm.
 * User: luuthieu
 * Date: 11/5/18
 * Time: 14:45
 */

use Shippo\Endpoints\LocationEndpoint;

class LocationEndpointTest extends BaseTest
{
    /**
     * @var LocationEndpoint
     */
    protected $endpoint;
    /**
     * @before
     */
    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->endpoint = new LocationEndpoint($this->getClient());
    }

    public function testGetLocationDetail()
    {
        $collection = $this->endpoint->get();
        $this->assertGreaterThan(0, $collection->count());
    }

    public function testGetLocations()
    {
        /** @var \Shippo\Models\Location[] $collection */
        $collection = $this->endpoint->get();
        $first = $collection[0];

        $location = $this->endpoint->detail($first->id);
        $this->assertEquals($first->name, $location->name, "Name match");
    }
}
