<?php
/**
 * Created by PhpStorm.
 * User: luuthieu
 * Date: 11/7/18
 * Time: 18:02
 */

class MerchantEndpointTest extends BaseTest
{
    /** @var \ShippoSDK\Endpoints\MerchantEndpoint */
    private $endpoint;

    /**
     * @before
     */
    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->endpoint = new \ShippoSDK\Endpoints\MerchantEndpoint($this->getClient());
    }

    public function testProfiles() {
        $merchant = $this->endpoint->profiles();
        $this->assertEquals('demo@gmail.com', $merchant->email);
    }
}